# -*- coding: utf-8 -*-
# (english gloss) -> (setting, bubble content)   FORMAT A — utterance
UTTER = {
 # --- formulas: no reply expected ---
 "Yes / no":("a plain civic office","a bold green tick and a bold red cross side by side"),
 "Excuse me, please…":("a busy pavement","a raised open palm, politely interrupting"),
 "I'm sorry":("a plain room, a dropped cup broken on the floor","a bowed head above the broken cup"),
 "No problem":("a plain doorway","an open relaxed palm and a small dismissive wave"),
 "Of course":("a plain office","a firm nodding head beside a bold tick"),
 "Just a moment":("a shop counter","a single raised index finger beside a small hourglass"),
 "Here you are":("a shop counter","two hands passing a wrapped parcel across"),
 "Welcome!":("a house doorway","two arms opened wide over an open door"),
 "Good luck!":("a doorway, a person leaving with a bag","a four-leaf clover and crossed fingers"),
 "Cheers!":("a plain table with two glasses","two raised glasses clinking"),
 "Bon appétit":("a table set with a steaming plate","a steaming plate flanked by a knife and fork"),
 "Happy birthday!":("a plain room","a birthday cake with lit candles"),
 "Congratulations!":("a plain hall","a pair of clapping hands beside a small rosette"),
 "Get well soon":("a bedside","a thermometer and a small bunch of flowers beside a bed"),
 "See you tomorrow":("a doorway at dusk","a waving hand beside a calendar page turning to the next day"),
 "Have a nice day":("a doorway in morning light","a rising sun above a small waving hand"),
 "Good luck on the trip":("a railway platform","a suitcase beside a waving hand and a departing train"),
 # --- core sentence patterns: the bubble carries the proposition ---
 "My name is Dainius":("a plain meeting room","a hand pointing at its own chest beside a blank name badge"),
 "I am from Lithuania":("a plain meeting room","a hand on the speaker's chest and a bold arrow to a small map of Lithuania"),
 "I live in Vilnius":("a plain street","a bold arrow from the speaker down into a house"),
 "I am twenty years old":("a plain room","a birthday cake beside a hand pointing at its own chest"),
 "I have a brother":("a plain room","the speaker's hand on their chest and beside it a second male figure"),
 "I don't have time":("a plain office","a clock struck through with a bold diagonal bar"),
 "I want to eat":("a plain kitchen","a hand on a stomach beside a plate of food"),
 "I would like coffee":("a café counter","a coffee cup with a polite open palm beneath it"),
 "I can speak a little":("a plain room","a small mouth speaking, with a thumb and finger held a little apart"),
 "I need water":("a plain kitchen","an empty glass beside a tap, with a bold arrow from tap to glass"),
 "I like this city":("a viewpoint over rooftops","a small whole heart above a city skyline"),
 "This is my house":("a plain street","a pointing hand and a house, joined by a bold short arrow"),
 "There is a shop here":("a plain street","a shop front with a bold arrow pointing down at the ground beside it"),
 "It is cold today":("a street in winter","a thermometer reading low beside a snowflake"),
 "What time is it?":("a plain street","a bold question mark beside a clock face"),
 "It is three o'clock":("a plain room","a clock face reading three o'clock"),
 "Where are you going?":("a plain street","a bold question mark beside a walking figure and a forked road"),
 "I am going home":("a plain street at dusk","a walking figure with a bold arrow to a lit house"),
 "I don't understand, sorry":("a plain room","a tangled knot of lines inside the bubble and a small shrug"),
 "I'm lost":("a street corner","a bold question mark over a street map held upside down"),
}
# (english) -> (setting, left-panel bubble, right-panel answer)  FORMAT B — exchange
EXCH = {
 "What is this?":("a market stall","a bold question mark beside a plain unlabelled box",
                  "the stallholder holding the box up and open, showing an apple inside"),
 "Who is that?":("a street corner","a bold question mark beside a faceless silhouette of a person",
                 "the companion pointing at a clearly drawn passer-by"),
 "Where is the toilet?":("a public corridor","a bold question mark beside a lavatory-door pictogram",
                         "the attendant pointing down the corridor to a plain lavatory door"),
 "How much is it?":("a market stall","a bold question mark beside a loaf of bread",
                    "the stallholder holding up coins on an open palm"),
 "How much does the ticket cost?":("a ticket window","a bold question mark beside a plain ticket",
                    "the clerk counting coins onto the counter beside a ticket"),
 "I don't speak Lithuanian":("a shop counter","a crossed-out speaking mouth",
                    "the shopkeeper nodding and speaking slowly with an open patient hand"),
 "A little":("a plain room","a thumb and finger held a small distance apart",
             "the other person nodding encouragingly"),
 "Please repeat":("a plain room","a circular arrow looping back on itself beside an ear",
                  "the other person speaking again, mouth open, one hand raised"),
 "Write it down, please":("a plain counter","a pencil poised over a blank notepad",
                          "the other person writing on the notepad and handing it over"),
 "What does it mean?":("a plain room","a bold question mark beside a blank speech scroll",
                       "the other person miming the meaning with both hands"),
 "How do you say … in Lithuanian?":("a plain room","a bold question mark beside an open mouth and a small flag",
                       "the other person speaking clearly, one finger raised"),
 "I need help":("a street","a raised open hand beside a bold exclamation",
                "a passer-by taking the person's arm to steady them"),
 "Call a doctor!":("a street, a person lying down","a telephone handset beside a medical cross",
                   "a bystander holding a telephone to their ear, hurrying"),
 "Where can I find…?":("a shop aisle","a bold question mark beside a shopping basket",
                       "the assistant pointing along the aisle to a shelf"),
}
